"use strict";
exports.__esModule = true;
var number1 = 10;
var number2 = 20;
var res;
res = number1 + number2;
res = number1 - number2;
res = number1 * number2;
res = number1 / number2;
console.log("Add: " + res);
console.log("Subtract: " + res);
console.log("Multiply: " + res);
console.log("Divide: " + res);
